name: C Shell CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3        # grab your code
      - name: Build Tiny Shell
        run: gcc scr/tsh.c -o tsh        # compile
      - name: Run smoke tests
        run: ./tsh < tests/t.sh          # sanity-check
